version: '3.11'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - './data/redis:/data'
    networks:
      - bot_network
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    env_file:
      - '.env'
    depends_on:
      - redis
    networks:
      - bot_network
    restart: unless-stopped

networks:
  bot_network:
    driver: bridge