"""0001

Revision ID: 2fe1e3768132
Revises: 
Create Date: 2024-06-21 19:14:23.057271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe1e3768132'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('user_values_table',
    sa.Column('user_left_id', sa.Integer(), nullable=False),
    sa.Column('value_right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_left_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['value_right_id'], ['values.id'], ),
    sa.PrimaryKeyConstraint('user_left_id', 'value_right_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_values_table')
    op.drop_table('values')
    op.drop_table('users')
    # ### end Alembic commands ###
